<?php

namespace Database\Seeders;

use App\Models\Food;
use App\Models\FoodCategory;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    public function run(): void
    {
        // ─── Food Categories ────────────────────────────────────────────
        $categories = $this->getCategories();
        $order = 1;

        foreach ($categories as $name) {
            FoodCategory::create([
                'name'       => $name,
                'sort_order' => $order++,
            ]);
        }

        // ─── Foods ──────────────────────────────────────────────────────
        $foods = $this->getFoods();
        $foodOrder = 1;

        foreach ($foods as [$name, $type]) {
            Food::create([
                'name'       => $name,
                'food_type'  => $type,
                'sort_order' => $foodOrder++,
            ]);
        }
    }

    private function getCategories(): array
    {
        return [
            // Categorías generales de alimentos
            'Frutas Aptas Sin Fructosa',
            'Algas',
            'Todas las Legumbres menos soja y cacahuete',
            'Quelantes',
            'Frutos rojos',
            'CG MEDIA-ALTA',
            'CG MEDIA',
            'CG BAJA',
            'ARROZ',
            'CEREALES',
            'PASTA',
            'GLUTEN',
            'INHIBEN O RETRASAN LA FASE I',
            'MEJORAR FASE 1',
            'DESCOMPONER HIF-1 ALFA',
            'FRENAR AROMATASA',
            'FAVORECEN EVACUACIÓN',
            'BRASSICAS',
            'BAJAR PURINAS - ACIDO ÚRICO',
            'MEJORAR FUNCIÓN HEPÁTICA DE LA BILIS',
            'SOLANÁCEAS',
            'RICOS EN ENZIMAS DIGESTIVAS',
            'ESTREÑIMIENTO',
            'ESTREÑIMIENTO (FRUTAS)',
            'ÁCIDOS',
            'ALCALINIZANTES',
            'AMARGOS Y DEPURATIVOS',
            'ANTICOAGULANTES',
            'ANTIHIPERTENSIVOS',
            'ANTIINFLAMATORIOS',
            'ASTRINGENTES',
            'COLAGOGOS',
            'DETOX Y DEPURATIVOS',
            'DIURÉTICOS',
            'FERMENTADOS',
            'INFLAMATORIOS',
            'PARA INCREMENTAR PLAQUETAS',
            'PRECURSORES DE NADH',
            'RICOS EN VITAMINA A (retinol)',
            'RICOS EN VITAMINA B6 (piridoxina)',
            'RICOS EN VITAMINA B9 (ác. fólico)',
            'RICOS EN VITAMINA B12 (cianocobalamina)',
            'ALIMENTOS RICOS EN VITAMINA C (ác. ascórbico)',
            'RICOS EN VITAMINA D (calciferol)',
            'RICOS EN VITAMINA E',
            'RICOS EN VITAMINA K1 (filoquinona)',
            'RICOS EN VITAMINA K2 (menaquinona)',
            'RICOS EN ANTIOXIDANTES',
            'RICOS EN ARGININA',
            'RICOS EN AZUFRE',
            'RICOS EN BETAINA',
            'RICOS EN BIOTINA',
            'RICO EN BORO',
            'RICO EN CALCIO',
            'RICOS EN CARNITINA',
            'RICOS EN CISTEÍNA',
            'RICOS EN COENZIMA Q10',
            'RICOS EN COLESTEROL',
            'RICOS EN COLINA',
            'RICOS EN CREATINA',
            'RICOS EN FENILALANINA',
            'RICOS EN FIBRA SOLUBLE',
            'RICOS EN FIBRA INSOLUBLE',
            'RICOS EN FITOESTRÓGENOS',
            'RICOS EN FLAVONOIDES',
            'RICOS EN FÓSFORO',
            'RICOS/PRECURSORES GABA',
            'RICOS EN GLICINA',
            'RICOS EN GLUTATIÓN',
            'RICOS EN HIERRO',
            'RICOS EN INULINA',
            'RICOS EN LICOPENO',
            'RICOS EN LISINA',
            'RICOS EN MAGNESIO',
            'RICOS EN MANGANESO',
            'RICOS EN METIONINA',
            'RICOS EN MOLIBDENO',
            'RICOS EN NÍQUEL',
            'RICOS EN OXALATOS',
            'RICOS EN POTASIO',
            'RICOS EN RESVERATROL',
            'RICOS EN RIBOSA',
            'RICOS EN RUTINA',
            'RICOS EN SELENIO',
            'RICOS EN SULFITOS',
            'RICOS EN TIROSINA',
            'RICOS EN TRIPTÓFANO',
            'RICOS EN YODO',
            'RICOS EN ZINC',
            'SUBEN ESTRÓGENOS',
            'BAJAN ESTRÓGENOS',
            'SUBEN PROGESTERONA',
            'ALTOS EN HISTAMINA',
            'BAJOS EN HISTAMINA',
            'AUMENTAN TESTOSTERONA',
            'BUENAS PARA EL RIÑÓN',
            'Fruta',
            'FRUTA EVITAR PIEDRAS RIÑÓN',
            'VERDURA CON MUCHOS HIDRATOS',
            'VERDURA CON MUCHA FIBRA',
            'VERDURA POBRE EN HIDRATOS',
            'PARA BAJAR GLUCOSA',
            'VERDURA MÁS FLATULENTA',
            'VERDURA CON MAYOR CARGA GLUCÉMICA',
            'PARA BAJAR COLESTEROL',
            'BAJAR TESTOSTERONA',
            'QUE GENERAN OXALATO CÁLCICO',
            'CON ALTA CARGA GLICÉMICA',
            'CARNE DE MAMÍFERO',
            'CARNE ROJA',
            'CARNE DE MONTE',
            'SETAS',
            'PESCADO AZUL GRANDE',
            'PESCADO AZUL PEQUEÑO',
            'PESCADO RICO EN OMEGA 3',
            'ALGAS CON POCA FIBRA',

            // Categorías de infusiones
            'Infusiones ACELERAR FASE II',
            'Infusiones ACNÉ',
            'Infusiones ACÚFENOS',
            'Infusiones ALCOHOLISMO',
            'Infusiones ALERGIAS',
            'Infusiones ANEMIA',
            'Infusiones ANISAKIASIS',
            'Infusiones ANSIOLÍTICAS',
            'Infusiones ANTIINFLAMATORIAS',
            'Infusiones ANTIHISTAMÍNICA',
            'Infusiones ANTIMICROBIANA',
            'Infusiones ANTIOXIDANTES',
            'Infusiones ARTRITIS',
            'Infusiones BAJAR ÁCIDO ÚRICO',
            'Infusiones BAJAR COLESTEROL',
            'Infusiones BAJAR ESTRÓGENOS Ortiga Verde',
            'Infusiones BAJAR ESTRÓGENOS Canela',
            'Infusiones BAJAR ESTRÓGENOS Sin Canela histaminosis',
            'Infusiones BAJAR ESTRÓGENOS cardo mariano sueño',
            'Infusiones BAJAR GLUCOSA',
            'Infusiones BAJAR TRIGLICÉRIDOS',
            'Infusiones CÁLCULOS BILIARES',
            'Infusiones CANDIDIASIS',
            'Infusiones CIRCULACIÓN',
            'Infusiones CISTITIS',
            'Infusiones COLON IRRITABLE',
            'Infusiones CONCENTRACIÓN',
            'Infusiones CONCILIAR EL SUEÑO Y LA ANSIEDAD',
            'Infusiones DERMATITIS ATÓPICA',
            'Infusiones DETOXIFICANTES',
            'Infusiones DIABETES',
            'Infusiones DIARREA',
            'Infusiones DIURÉTICAS',
            'Infusiones DISPEPSIA',
            'Infusiones EDEMAS',
            'Infusiones EMBARAZO (APTAS)',
            'Infusiones EMBARAZO (NO APTAS)',
            'Infusiones ESTREÑIMIENTO',
            'Infusiones EXPECTORANTES',
            'Infusiones FAVORECER LA FUNCIONALIDAD HEPÁTICA',
            'Infusiones FLATULENCIAS',
            'Infusiones GARGANTA',
            'Infusiones GASES',
            'Infusiones GASTRITIS',
            'Infusiones HEMORROIDES',
            'Infusiones HEPATITIS',
            'Infusiones HERNIA DE HIATO',
            'Infusiones HINCHAZÓN',
            'Infusiones HIPERTENSIÓN',
            'Infusiones HIPOTENSIÓN',
            'Infusiones HIPOTIROIDISMO',
            'Infusiones INAPETENCIA (FALTA DE APETITO O ANOREXIA)',
            'Infusiones INHIBEN O RETRASAN LA FASE I',
            'Infusiones HISTAMINOSIS',
            'Infusiones MENOPAUSIA y bochornos',
            'Infusiones MENSTRUACIÓN ALTERACIONES',
            'Infusiones MEJORAR LA PIEL',
            'Infusiones MEJORAR FUNCIÓN DIGESTIVA',
            'Infusiones MEJORAR FUNCIÓN RIÑÓN',
            'Infusiones MIGRAÑA',
            'Infusiones OSTEOPOROSIS',
            'Infusiones PARÁSITOS',
            'Infusiones PARA DESCOMPONER HIF-1 ALFA',
            'Infusiones PERDER PESO',
            'Infusiones PRÓSTATA',
            'Infusiones PROTECTORAS GÁSTRICAS',
            'Infusiones PROTECTORAS INTESTINALES',
            'Infusiones QUITAR PIEDRAS DEL RIÑÓN',
            'Infusiones SISTEMA INMUNE',
            'Infusiones SUBIR ESTRÓGENOS',
            'Infusiones SUBIR PROGESTERONA',
            'Infusiones URTICARIA',
            'Infusiones VESÍCULA BILIAR INSUFICIENCIA',
            'Infusiones VEJIGA',
            'Infusiones Base',
        ];
    }

    private function getFoods(): array
    {
        return [
            ['abadejo', 'Pescado blanco'],
            ['abedul', 'Café e infusiones'],
            ['acacia', 'Café e infusiones'],
            ['acedía', 'Pescado blanco'],
            ['aceitunas', 'Encurtidos'],
            ['acelga', 'Verduras y hortalizas'],
            ['achicoria', 'Verduras y hortalizas'],
            ['achicoria', 'Café e infusiones'],
            ['agar agar', 'Algas'],
            ['aguacate', 'Fruta'],
            ['ajenjo', 'Café e infusiones'],
            ['ajo blanco', 'Verduras y hortalizas'],
            ['ajo morado', 'Verduras y hortalizas'],
            ['ajo negro', 'Verduras y hortalizas'],
            ['alaria', 'Algas'],
            ['albahaca', 'Especias'],
            ['albaricoque', 'Fruta'],
            ['alcachofa', 'Verduras y hortalizas'],
            ['alcachofa', 'Café e infusiones'],
            ['alcachofera', 'Café e infusiones'],
            ['alcaparras', 'Encurtidos'],
            ['alcaravea', 'Café e infusiones'],
            ['alfalfa', 'Café e infusiones'],
            ['almeja fina', 'Marisco'],
            ['almendra', 'Bebidas vegetales'],
            ['almendras', 'Frutos secos'],
            ['aloe vera', 'Verduras y hortalizas'],
            ['aloe vera', 'Café e infusiones'],
            ['alpiste', 'Bebidas vegetales'],
            ['alquequenje', 'Fruta'],
            ['amanita caesarea', 'Setas'],
            ['amaranto', 'Cereales'],
            ['anacardo', 'Frutos secos'],
            ['anacardos', 'Bebidas vegetales'],
            ['anchoas', 'Pescado Azul'],
            ['angélica', 'Café e infusiones'],
            ['anguila', 'Pescado Azul'],
            ['anís', 'Especias'],
            ['anís', 'Café e infusiones'],
            ['anís estrellado', 'Especias'],
            ['apio', 'Verduras y hortalizas'],
            ['apio', 'Café e infusiones'],
            ['arame', 'Algas'],
            ['arándano', 'Fruta'],
            ['arenaria', 'Café e infusiones'],
            ['arenque', 'Pescado Azul'],
            ['arroz', 'Cereales'],
            ['arroz', 'Bebidas vegetales'],
            ['arroz blanco refinado', 'Arroz'],
            ['artemisa', 'Café e infusiones'],
            ['ashwagandha', 'Café e infusiones'],
            ['atún fresco', 'Pescado Azul'],
            ['avellana', 'Bebidas vegetales'],
            ['avellanas', 'Frutos secos'],
            ['avena', 'Cereales'],
            ['avena', 'Pan'],
            ['avena (sin gluten)', 'Bebidas vegetales'],
            ['azafrán', 'Especias'],
            ['azuki', 'Legumbres'],
            ['bacaladilla', 'Pescado blanco'],
            ['bacalao', 'Pescado blanco'],
            ['banderillas', 'Encurtidos'],
            ['bardana', 'Café e infusiones'],
            ['basmati', 'Arroz'],
            ['bayas de goji', 'Fruta'],
            ['bebidas alcohólicas destiladas', 'Café e infusiones'],
            ['bechamel', 'Productos lácteos'],
            ['berberecho', 'Marisco'],
            ['berberina', 'Café e infusiones'],
            ['berenjena', 'Verduras y hortalizas'],
            ['berenjenas en vinagre', 'Encurtidos'],
            ['berro', 'Verduras y hortalizas'],
            ['bígaro', 'Marisco'],
            ['bimi', 'Verduras y hortalizas'],
            ['boldo', 'Café e infusiones'],
            ['boletus', 'Setas'],
            ['boniato o batata', 'Tubérculos'],
            ['bonito', 'Pescado Azul'],
            ['boquerón', 'Pescado Azul'],
            ['borraja', 'Verduras y hortalizas'],
            ['brócoli', 'Verduras y hortalizas'],
            ['brotes de todo tipo', 'Verduras y hortalizas'],
            ['buey', 'Carne Roja'],
            ['buey de mar', 'Marisco'],
            ['caballa', 'Pescado Azul'],
            ['caballo', 'Carne Roja'],
            ['cabra', 'Carne Roja'],
            ['cacahuete', 'Legumbres'],
            ['cacahuete', 'Aceite'],
            ['cacahuetes', 'Frutos secos'],
            ['cacao', 'Fruta'],
            ['Cacao Puro', 'Dulces y Chocolate'],
            ['café con cafeína', 'Café e infusiones'],
            ['calabacín blanco', 'Verduras y hortalizas'],
            ['calabacín verde', 'Verduras y hortalizas'],
            ['calabaza', 'Tubérculos'],
            ['calamar', 'Marisco'],
            ['caléndula', 'Café e infusiones'],
            ['camarones', 'Marisco'],
            ['canela', 'Café e infusiones'],
            ['canela de Ceylán', 'Especias'],
            ['canela+laurel', 'Café e infusiones'],
            ['cangrejos', 'Marisco'],
            ['canola', 'Aceite'],
            ['canónigos', 'Verduras y hortalizas'],
            ['cañailla', 'Marisco'],
            ['cáñamo', 'Bebidas vegetales'],
            ['cáñamo', 'Aceite'],
            ['caqui', 'Fruta'],
            ['cardamomo', 'Especias'],
            ['cardamomo', 'Café e infusiones'],
            ['cardo mariano', 'Café e infusiones'],
            ['cardos', 'Verduras y hortalizas'],
            ['carragaheen', 'Algas'],
            ['castaña', 'Frutos secos'],
            ['castaño de indias', 'Café e infusiones'],
            ['cazón', 'Pescado Azul'],
            ['cebada', 'Cereales'],
            ['cebolla blanca', 'Verduras y hortalizas'],
            ['cebolla dulce', 'Verduras y hortalizas'],
            ['cebolla morada', 'Verduras y hortalizas'],
            ['Cebollitas', 'Encurtidos'],
            ['centeno', 'Cereales'],
            ['centeno puro', 'Pan'],
            ['centollo', 'Marisco'],
            ['cerdo', 'Carne Roja'],
            ['cereza', 'Fruta'],
            ['cerveza con alcohol', 'Café e infusiones'],
            ['cerveza sin alcohol', 'Café e infusiones'],
            ['champiñón', 'Setas'],
            ['chicharro o jurel', 'Pescado Azul'],
            ['chipirones', 'Marisco'],
            ['chirimoya', 'Fruta'],
            ['chirla', 'Marisco'],
            ['chlorella en polvo', 'Algas'],
            ['chocolate sólo si supera el 85%', 'Dulces y Chocolate'],
            ['chukrut no pasteurizado', 'Encurtidos'],
            ['ciervo', 'Carne Roja'],
            ['cigalas', 'Marisco'],
            ['cilantro ecológico', 'Especias'],
            ['ciprés', 'Café e infusiones'],
            ['ciruela', 'Fruta'],
            ['ciruela pasa', 'Fruta'],
            ['claras de huevo', 'Huevos'],
            ['clavo', 'Especias'],
            ['clavo', 'Café e infusiones'],
            ['cochayuyo', 'Algas'],
            ['coco', 'Fruta'],
            ['coco', 'Bebidas vegetales'],
            ['coco ecológico', 'Aceite'],
            ['codorniz', 'Carne blanca'],
            ['col china', 'Verduras y hortalizas'],
            ['col de Bruselas', 'Verduras y hortalizas'],
            ['col rizada', 'Verduras y hortalizas'],
            ['col roja', 'Verduras y hortalizas'],
            ['col verde', 'Verduras y hortalizas'],
            ['cola de caballo', 'Café e infusiones'],
            ['coliflor', 'Verduras y hortalizas'],
            ['comino', 'Especias'],
            ['conejo', 'Carne blanca'],
            ['congrio', 'Pescado Azul'],
            ['coquina', 'Marisco'],
            ['cordero', 'Carne Roja'],
            ['corteza de naranjo amargo', 'Café e infusiones'],
            ['críptolepis', 'Café e infusiones'],
            ['cuajada', 'Productos lácteos'],
            ['cúrcuma', 'Especias'],
            ['cúrcuma', 'Café e infusiones'],
            ['cúrcuma + pimienta', 'Especias'],
            ['cúrcuma+pimienta', 'Café e infusiones'],
            ['curry', 'Especias'],
            ['dátiles', 'Fruta'],
            ['de algas', 'Pasta y pizzas'],
            ['de cerdo', 'Embutidos'],
            ['de legumbres', 'Pasta y pizzas'],
            ['de trigo sarraceno o sin gluten', 'Pasta y pizzas'],
            ['desmodium', 'Café e infusiones'],
            ['diente de león', 'Café e infusiones'],
            ['dorada', 'Pescado blanco'],
            ['dulce', 'Algas'],
            ['dulces chicles caramelos etc', 'Dulces y Chocolate'],
            ['embutido de ciervo', 'Embutidos'],
            ['embutido de pavo y de pollo', 'Embutidos'],
            ['emperador', 'Pescado Azul'],
            ['endivia', 'Verduras y hortalizas'],
            ['enebro', 'Café e infusiones'],
            ['eneldo', 'Especias'],
            ['equinácea', 'Café e infusiones'],
            ['escaramujo', 'Café e infusiones'],
            ['escarola', 'Verduras y hortalizas'],
            ['espárrago', 'Verduras y hortalizas'],
            ['espelta', 'Cereales'],
            ['espelta', 'Pan'],
            ['espelta', 'Bebidas vegetales'],
            ['espinaca', 'Verduras y hortalizas'],
            ['espino blanco', 'Café e infusiones'],
            ['espirulina', 'Algas'],
            ['estévia', 'Café e infusiones'],
            ['estragón', 'Especias'],
            ['eucalipto', 'Café e infusiones'],
            ['faisán', 'Carne Roja'],
            ['farro', 'Cereales'],
            ['fenogreco', 'Especias'],
            ['fenogreco', 'Café e infusiones'],
            ['filete de hígado de cordero', 'Carne Roja'],
            ['filete de hígado de ternera', 'Carne Roja'],
            ['fletán', 'Pescado blanco'],
            ['frambuesa', 'Fruta'],
            ['fresa', 'Fruta'],
            ['gallo', 'Pescado blanco'],
            ['gambas', 'Marisco'],
            ['garbanzos', 'Legumbres'],
            ['garbanzos tostados', 'Frutos secos'],
            ['ginseng', 'Café e infusiones'],
            ['granada', 'Fruta'],
            ['grosella', 'Fruta'],
            ['guayaba', 'Fruta'],
            ['guisantes', 'Legumbres'],
            ['habas', 'Legumbres'],
            ['habas tostadas', 'Frutos secos'],
            ['helados', 'Productos lácteos'],
            ['hibisco', 'Café e infusiones'],
            ['hierba luisa', 'Café e infusiones'],
            ['hierbabuena', 'Especias'],
            ['higaditos de pollo', 'Carne blanca'],
            ['higo chumbo', 'Fruta'],
            ['hinojo', 'Verduras y hortalizas'],
            ['hinojo', 'Especias'],
            ['hinojo', 'Café e infusiones'],
            ['hiziki', 'Algas'],
            ['huevos', 'Huevos'],
            ['integral', 'Arroz'],
            ['jamón de pato', 'Embutidos'],
        ];
    }
}
