<?php

namespace Database\Seeders;

use App\Models\CatalogItem;
use App\Models\CatalogSection;
use Illuminate\Database\Seeder;

class SupplementSeeder extends Seeder
{
    public function run(): void
    {
        $sections = $this->getSections();

        $sectionOrder = 100;

        foreach ($sections as $sectionData) {
            $section = CatalogSection::create([
                'slug'       => $sectionData['slug'],
                'name'       => $sectionData['name'],
                'group'      => $sectionData['group'],
                'sort_order' => $sectionOrder++,
            ]);

            $itemOrder = 1;
            foreach ($sectionData['items'] as $label) {
                CatalogItem::create([
                    'catalog_section_id' => $section->id,
                    'label'              => $label,
                    'sort_order'         => $itemOrder++,
                ]);
            }
        }
    }

    private function getSections(): array
    {
        return [
            // ─── Suplementación Habitual ─────────────────────────────────
            [
                'slug'  => 'suplementacion_habitual',
                'name'  => 'Suplementación Habitual',
                'group' => 'suplementacion',
                'items' => [
                    'Aceite de comino negro de Equisalud (1-1-1)',
                    'Aceite de orégano de Solaray',
                    'BERBERINA DE SOLARAY (1-1-1)',
                    'Bisglicinato de magnesio de EFNE (1-1-1)',
                    'Bisglicinato de magnesio Méderi (1-1-1)',
                    'Citrato de magnesio de Bonusan (1-1-1)',
                    'D-MANOSA 1000 mg de Solaray (0-0-1)',
                    'Extracto de semilla de pomelo de Derbós',
                    'Gastrileo de Méderi',
                    'Gut Motility de Enzymedica Procinético (0-1-1)',
                    'L-Treonato de magnesio de KAL (0-0-1)',
                    'L-Treonato de magnesio de KAL (1-0-1)',
                    'Para-Sit de Suravitasan',
                    'Paracys de Méderi',
                    'Peróxido de magnesio (ozovit)',
                    'Superenzimes de KAL',
                ],
            ],

            // ─── Suplementación ──────────────────────────────────────────
            [
                'slug'  => 'suplementacion',
                'name'  => 'Suplementación',
                'group' => 'suplementacion',
                'items' => [
                    'ÁCIDO ÚRICO. Total Cleanse Uric acid de Solaray',
                    'ÁCIDO ÚRICO. Uriprinol',
                    'ADICCIONES. Naturlider kudzulider cápsulas',
                    'AGUA DE MAR. Holoslife zona afectada',
                    'AGUA DE MAR. Ibiza y Formentera',
                    'AGUA DE MAR. ¿Cómo tomarla?',
                    'AGUA DE MAR. Aquamaris',
                    'AGUA DE MAR. Holoslife',
                    'AGUA DE MAR. Holoslife estreñimiento',
                    'AGUA DE MAR. Ormus Marino',
                    'Alergias agudas. Aflugenex',
                    'ALOPECIA. Epilobio',
                    'ALOPECIA. Stiproxal champu',
                    'Alteraciones del sueño. Serobrain',
                    'ALZHEIMER Y PARKINSON. Aceite de Coco Virgen',
                    'ALZHEIMER Y PARKINSON. Acugen Q10 Spray de laboratorios Glauber',
                    'ALZHEIMER Y PARKINSON. AtreMorine de Biotech',
                    'ALZHEIMER Y PARKINSON. Berberina Aristata de CFN',
                    'ALZHEIMER Y PARKINSON. Berberina de Solaray',
                    'ALZHEIMER Y PARKINSON. Cúrcuma longa de Bonusan',
                    'ALZHEIMER Y PARKINSON. Hoja de olivo de sura vitasan',
                    'ALZHEIMER Y PARKINSON. insulina intranasal',
                    'ALZHEIMER Y PARKINSON. Mico Leo de Hifas da Terra',
                    'ALZHEIMER Y PARKINSON. Mucuna pruriens de Bonusan',
                    'ALZHEIMER Y PARKINSON. NUTIMETIL-B COMPLEX DE NUTILAB',
                    'ALZHEIMER Y PARKINSON. plasma de Quinton isotónico',
                    'ALZHEIMER Y PARKINSON. Resveratrol de Bonusan',
                    'ALZHEIMER Y PARKINSON. Seriobioma',
                    'ALZHEIMER Y PARKINSON. Vitamina C en comprimidos masticables',
                    'ALZHEIMER Y PARKINSON. VITAMINA D3 LÍQUIDA',
                    'ANEMIA. Floradix jarabe hierro salud',
                    'ANEMIA. Haematonyl de Bonusan',
                    'ANEMIA. Hemaferrina de Méderi',
                    'ANTIOX. Coenzima Q10 de Sotya',
                    'ANTIOX. Immunocal de Immunotec',
                    'ANTIOX. Liposomal Glutation de Curesupport',
                    'ANTIOX. PQQ de Now 20mg',
                    'ANTIOX. PQQ+ coQ10 de Solaray',
                    'ANTIOX. Super resveratrol de Solaray 1-1-0',
                    'ANTIOX. Trans-resveratrol',
                    'ANTIOX. moringa',
                    'ARTRITIS/ARTROSIS. Artro-Duo Forte de Méderi',
                    'ARTRITIS/ARTROSIS. Extracto de Harpagofito de SoriaNatural',
                    'ARTRITIS/ARTROSIS. Harpagofito de HSN (0-1-1)',
                    'AUMENTAR ACIDEZ GÁSTRICA. Clorhidrato de betaína',
                    'BAÑOS DE ASIENTO FRÍO',
                    'BLOQUEO RECEPTOR NMDA. GABA',
                    'BLOQUEO RECEPTOR NMDA. Magnesio',
                    'BLOQUEO RECEPTOR NMDA. MSM',
                    'BLOQUEO RECEPTOR NMDA. SAMe',
                    'BLOQUEO RECEPTOR NMDA. Zinc',
                    'BONUSAN. cPNI-10D',
                    'BONUSAN. cPNI-10S',
                    'BONUSAN. cPNI-11D',
                    'BONUSAN. cPNI-11S',
                    'BONUSAN. cPNI-12D',
                    'BONUSAN. cPNI-12S',
                    'BONUSAN. cPNI-13D',
                    'BONUSAN. cPNI-13S',
                    'BONUSAN. cPNI-14D',
                    'BONUSAN. cPNI-14S',
                    'BONUSAN. cPNI-1U',
                    'BONUSAN. cPNI-2U',
                    'BONUSAN. cPNI-3U',
                    'BONUSAN. cPNI-4U',
                    'BONUSAN. cPNI-5U',
                    'BONUSAN. cPNI-6D',
                    'BONUSAN. cPNI-6S',
                    'BONUSAN. cPNI-7U',
                    'BONUSAN. cPNI-8U',
                    'BONUSAN. cPNI-9D',
                    'BONUSAN. cPNI-9S',
                    'CAMBIAR SISTEMA INMUNE A METABOLISMO AERÓBICO. cPNI-8U',
                    'CAMBIAR SISTEMA INMUNE A METABOLISMO AERÓBICO. Molibdeno + Manganeso-Chorella',
                    'CAMBIAR SISTEMA INMUNE A METABOLISMO AERÓBICO. Ribosa',
                    'CANDIDIASIS. GSE ÍNTIMO PRO-ÓVULOS SEMILLA DE POMELO',
                    'CARDIACOS Y CIRCULATORIOS. L-Lisina en polvo',
                    'CICATRIZACIÓN DE HERIDAS. Sangre de drago',
                    'CIERRE MUCOSAS. Glutamina',
                    'CIERRE MUCOSAS. Si patógenos',
                    'CIERRE MUCOSAS. Vit C',
                    'CIERRE MUCOSAS. Vit D3',
                    'COLICO DEL LACTANTE Y ANIMO. BioGaia Reuteri Gotas',
                    'Colitis ulcerosa y Crohn fase de mantenim. Acronelle',
                    'Colitis ulcerosa y Crohn fase de mantenim. Serobioma',
                    'Colon irritable. Enterelle + Serobioma + Acronelle',
                    'COMPLEMENTO BIBERÓN. cPNI-4U',
                    'CREMA PICOR PIEL. LIPIKAR BAUME AP+M',
                    'CURACIÓN HERIDAS. Resoleomics',
                    'CURACIÓN HERIDAS. Vit C ascorbato',
                    'CÚRCUMA. CURCUMIN ST de CFN',
                    'CÚRCUMA. Lamberts',
                    'CÚRCUMA. liposomada de Curesupport',
                    'CÚRCUMA. liposomada de Equisalud',
                    'CÚRCUMA. Orwux de EFNE',
                    'DÉFICIT DE CRECIMIENTO. Precursor de GH de Anastore',
                    'Déficit inmunitario. Citogenex',
                    'Depresión. Serobioma y Serobrain + Serobrain',
                    'Dermatitis eccema acné. Enterelle + Ramnoselle + Citogenex',
                    'DERMATITIS. Baños con probióticos',
                    'DERMATITIS. Lisina',
                    'DERMATITIS. Vit C',
                    'DERMATITIS. Vit D',
                    'Dermatits atópica y Psoriasis. Enterelle + Serobioma + Citogenex',
                    'DESCOMPOSICIÓN HIF-1. Selenio Zinc Molibdeno',
                    'DESCOMPOSICIÓN HIF-1. Vit C',
                    'DETERIORO COGNITIVO Y DEPRESIÓN. Crocus sativa extracto',
                    'DETERIORO COGNITIVO Y DEPRESIÓN. Doxiciclina 25 mg',
                    'DETERIORO COGNITIVO Y DEPRESIÓN. G.S Calm de Solaray',
                    'DETERIORO COGNITIVO Y DEPRESIÓN. L-phenylalanina 500mg de Solaray',
                    'DETERIORO COGNITIVO Y DEPRESIÓN. Melatonina',
                    'DETERIORO COGNITIVO Y DEPRESIÓN. Mucuna pruriens de Bonusan',
                    'DETOX. vinagre de manzana con las comidas',
                    'DETOX. Chlorella en cápsulas de SuraVitasan',
                    'DETOX. Cilantro Heavy Metal de Planetari Herbals',
                    'DETOX. Flex soll para sulfatación',
                    'DETOX. Hifas-Detox',
                    'DETOX. Liver support fórmula de Smart',
                    'DETOX. MetalDetox de suravitasan',
                    'DETOX. METIL ACCIÓN de Eglé',
                    'Diabetes. Glycinet',
                    'Diabetes. Serobioma',
                    'Disbiosis intestinal y reimplantología. Bifiselle',
                    'Disbiosis intestinal y reimplantología. Enterelle',
                    'Disbiosis intestinal y reimplantología. Ramnoselle',
                    'Disbiosis intestinal y reimplantología. Serobioma',
                    'Dispepsia. Plasma isotónico de Quinton',
                    'Distensión abdominal y disbiosis. Enterelle + Adomelle',
                    'Diverticulitis. ENTERELLE + RAMNOSELLE',
                    'DOLOR INFLAMATORIO. Lactoferrina',
                    'DOLOR INFLAMATORIO. Omega 3',
                    'DOLOR INFLAMATORIO. PEA',
                    'DOLOR INFLAMATORIO. Vit E Curcuma Resveratrol',
                    'DOLOR NEUROPÁTICO ESTREÑIMIENTO DOLOROSO LA GRASA NO SACIA. PEA',
                    'DOLOR. Aceite de CBD 15% de SATIVIDA',
                    'DOLOR. Aceite de CBD de 3000mg de CFN',
                    'DOLOR. ARAGESIC',
                    'DOLOR. Bisciglinato de magnesio de EFNE',
                    'DOLOR. Citrameder B6 de Méderi',
                    'DOLOR. CITRATO DE MAGNESIO DE BONUSAN',
                    'DOLOR. cPNI-1U de Bonusan',
                    'DOLOR. Equisalud Holoram cronisol-D',
                    'DOLOR. MAGNESAN FORTE PLUS DE BONUSAN',
                    'DOLOR. Mitochondrial Active LCN',
                    'DOLOR. Myolax',
                    'DOLOR. PEA (Palmitoiletanolamida) DE BONUSAN',
                    'DOLOR. Rotufib',
                    'DOLOR. Superibuactin',
                    'DOLOR. Tiobec Dol',
                    'Dosis diaria recomendada',
                    'EJE HPG. Cimifuga racemosa',
                    'EJE HPG. cPNI-1U',
                    'EJE HPG. Crocus Sativus',
                    'EJE HPG. Hypericum perforatum',
                    'EJE HPG. Mucuna pruriens',
                    'EJE HPG. Vitex Agnus Castus extracto',
                    'EJE HPT (ESTIMULACIÓN). Ácido alfa lipólico',
                    'EJE HPT (ESTIMULACIÓN). cPNI-10D',
                    'EJE HPT (ESTIMULACIÓN). cPNI-10S',
                    'EJE HPT (ESTIMULACIÓN). Niacina',
                    'EJE HPT (ESTIMULACIÓN). Selenio',
                    'EJE HPT (ESTIMULACIÓN). Tyronyl',
                    'EJE HPT (ESTIMULACIÓN). Vit C',
                    'EJE HPT (ESTIMULACIÓN). Vit E',
                    'EJE HPT (ESTIMULACIÓN). Yodo',
                    'EJE HPT (ESTIMULACIÓN). Zinc',
                    'ELIMINAR NEU5GC. Lactoferrina',
                    'EMBARAZO. Ácido fólico',
                    'Embarazo. Bifiselle',
                    'EMBARAZO. Colina',
                    'EMBARAZO. Magnesio potasio',
                    'EMBARAZO. Multivitamínico',
                    'EMBARAZO. Omega 3',
                    'EMBARAZO. Vit D',
                    'EMBARAZO. Yodo',
                    'EMBARAZO. Zinc y Vit C',
                    'ENEMA DE CAFÉ',
                    'ENERGÍA. Ribosa en polvo + magnesio de Suravitasan',
                    'ENZIMAS/HISTAMINOSIS/FRUCTOSA. DAOfood',
                    'ENZIMAS/HISTAMINOSIS/FRUCTOSA. Daosin',
                    'ENZIMAS/HISTAMINOSIS/FRUCTOSA. FRUCTAID',
                    'ENZIMAS/HISTAMINOSIS/FRUCTOSA. Fructoaid de Pronatura',
                    'ENZIMAS/HISTAMINOSIS/FRUCTOSA. Gastrozym',
                    'ENZIMAS/HISTAMINOSIS/FRUCTOSA. MyDao de Ysana',
                    'ENZIMAS/HISTAMINOSIS/FRUCTOSA. Superenzymes',
                    'ESTIMULACIÓN DE PROGESTERONA. Cimicifuga racemosa de Bonusan',
                    'ESTIMULACIÓN DE PROGESTERONA. Cimicifuga racemosa extracto de Bonusan',
                    'ESTIMULACIÓN DE PROGESTERONA. L-Arginina en polvo de Bulk Powders',
                    'ESTIMULACIÓN DE PROGESTERONA. Melatonina sueño de Aquilea',
                    'ESTIMULACIÓN DE PROGESTERONA. Natural Progesterone Cream',
                    'ESTIMULACIÓN DE PROGESTERONA. Onagra y borraja de CFN',
                    'ESTIMULACIÓN DE PROGESTERONA. Vitamina E 600mg',
                    'ESTIMULACIÓN DE PROGESTERONA. Vitex agnus castus de CFN',
                    'ESTREÑIMIENTO. Aliviolax fisiolax',
                    'ESTREÑIMIENTO. aloe vera + zumo de naranja',
                    'ESTREÑIMIENTO. Peróxido de magnesio de CFN',
                    'ESTREÑIMIENTO. Psyllium de Solgar',
                    'Estreñimiento. Xantonet + Bifiselle + Serobioma + Xantonet',
                    'FALTA DE ENERGÍA. Chorella',
                    'FALTA DE ENERGÍA. Creatina fosfatasa',
                    'FALTA DE ENERGÍA. Magnesio',
                    'FALTA DE ENERGÍA. Ribosa',
                    'FALTA DE MOTIVACIÓN. Mucuna Pruriens',
                    'FIBROMIALGIA. Anatomía',
                    'FIBROMIALGIA. Neuroinflamación',
                    'FIBROMIALGIA. Neurotransmisores',
                    'Fibromialgia. Serobioma',
                    'FRENAR LA AROMATASA. Cranberry complex de Airbiotic',
                    'FRENAR LA AROMATASA. Infusiones de Ginkgo Biloba',
                    'FRENAR LA AROMATASA. Licopeno+ortiga y zinc de Terranova',
                    'FRENAR LA AROMATASA. Mangosteen extract de Solaray',
                    'FRENAR LA AROMATASA. Melatonina Aquilea sueño',
                    'FRENAR LA AROMATASA. Vitamina D 4000 ui de Nutilab',
                    'FRENAR RESPUESTA INFLAMATORIA POSPRANDIAL. cPNI-3U',
                    'GARGANTA RESPIRATORIOS. aceite esencial de tomillo',
                    'GARGANTA RESPIRATORIOS. Barberry de nutramedix',
                    'GARGANTA RESPIRATORIOS. Drasanvi Promelo Spray Oral',
                    'GARGANTA RESPIRATORIOS. Miel de manuka UMF> 13',
                    'GARGANTA RESPIRATORIOS. SOS Active de Tongil',
                    'Gastritis/reflujo/hernia de hiato/esofagitis. Pilorex',
                    'Gripe faringitis y bronquitis. Aflugenex + citogenex',
                    'Hepatopatías y esteatosis hepática. Enterelle + Serobioma + Bifiselle + Milonet',
                    'HERPES ZOSTER CITOMEGALOVIRUS Y VIRUS DEL PAPILOMA HUMANO. Takuna de Nutramedix',
                    'HIFAS DA TERRA. Bio-Defense',
                    'HIFAS DA TERRA. Bio-Intestin',
                    'HIFAS DA TERRA. Dr. GB',
                    'HIFAS DA TERRA. Dr. Immune Five',
                    'HIFAS DA TERRA. Hifas-Detox',
                    'HIFAS DA TERRA. Hifas-Microbiota',
                    'HIFAS DA TERRA. HIFAS-Equilibrium',
                    'HIFAS DA TERRA. Mico Fiv',
                    'HIFAS DA TERRA. Mico Mama 2.0',
                    'HIFAS DA TERRA. Mico onco',
                    'HIFAS DA TERRA. Mico Repair',
                    'HIFAS DA TERRA. Mico Vir+',
                    'HIFAS DA TERRA. Mico-Mix',
                    'HIFAS DA TERRA. Mico-RT',
                    'HÍGADO. Ácido alfa lipoico',
                    'HÍGADO. Ácido málico en cápsulas',
                    'HÍGADO. Azufrados glutatión NAC L-cisteína metionina L-lisina',
                    'HÍGADO. Chorella',
                    'HÍGADO. Mg vs Al',
                    'HÍGADO. Se vs Hg',
                    'HÍGADO. Vinagre de manzana ECO',
                    'HÍGADO. Zn vs Cd',
                    'HIPERTENSIÓN. BP Defense de KAL',
                    'Hipotiroidismo. Enterelle + Serobioma + Citogenex',
                    'HORMONAL SUST. ESTRÓGENOS. Phyto estrogen cream de Super Smart',
                    'HORMONAL SUST. ESTRÓGENOS. Phytoestrogen plus de Solaray',
                    'HUESO. Ácido fólico B6 SAMe',
                    'HUESO. Vitamina K2 + K1',
                    'INFERTILIDAD. Complejo B activo + Vit B',
                    'INFLAMACIÓN HIPOTÁLAMO. cPNI-1U',
                    'INFLAMACIÓN HIPOTÁLAMO. PEA',
                    'INHIB MIOSTATINAS. CREATINA MONOHIDRATO MY PROTEIN',
                    'INHIB MIOSTATINAS. EVOEPIC MUSCLE de HSN',
                    'INHIB MIOSTATINAS. GREEN TEA 2750 mg de Lamberts',
                    'INHIBIR AROMATASA. Allium Sativum',
                    'INHIBIR AROMATASA. Vitex Agnus Castus',
                    'INHIBIR RECAPTACIÓN DE DOPAMINA POR SISTEMA INMUNE. cPNI-6D',
                    'INHIBIR RECAPTACIÓN DE SEROTONINA POR SISTEMA INMUNE. cPNI-6S',
                    'INHIBIR RECAPTACIÓN DE SEROTONINA POR SISTEMA INMUNE. Crocus Sativus',
                    'INSOMNIO. Alcalin-C de Eglé',
                    'INSOMNIO. Circadin',
                    'INSOMNIO. Derbós plataggio IS ampollas',
                    'INSOMNIO. Dormed de Méderi',
                    'INSOMNIO. Dormo Rem de Synestia',
                    'INSOMNIO. Glicina en cápsulas de Méderi',
                    'INSOMNIO. Glicina en polvo HSN RAW POWDER',
                    'INSOMNIO. LKN Phyto TS',
                    'INSOMNIO. Melanoctina',
                    'INSOMNIO. Melatonina de Synestia o Aquilea',
                    'INSOMNIO. Melatonina fórmula magistral 5 Caballeros',
                    'INSOMNIO. NREM SLEEPP de CFN',
                    'INSOMNIO. Oniria',
                    'INSOMNIO. Redimel de Glauber pharma',
                    'INSOMNIO. Ribosa en polvo de CFN',
                    'INSOMNIO. Ribosa en polvo de EFNE',
                    'Intolerancia a la histamina. Aflugenex de Bromatech',
                    'Intolerancias alimenticias. Acronelle',
                    'Intolerancias alimenticias. Serobioma',
                    'JENGIBRE. deshidratado sin azúcar',
                    'JENGIBRE. Ginger 12000 de Lamberts',
                    'JENGIBRE. ST de CFN (1-1-1)',
                    'LINEA NUTERGIA Ergystress',
                    'LINEA NUTERGIA. Ergycalm',
                    'LINEA NUTERGIA. Ergyclean',
                    'LINEA NUTERGIA. Ergycox',
                    'LINEA NUTERGIA. Ergydren',
                    'LINEA NUTERGIA. Ergyren',
                    'LINEA NUTERGIA. Ergyviol',
                    'LOMBRICES. Lombritox de Phytovit',
                    'MACRÓFAGOS Y NEUTRÓFILOS. Vit C',
                    'MAGNESIO. Bisglicinato de magnesio',
                    'MAGNESIO. Bisglicinato de magnesio de Synestia',
                    'MAGNESIO. Citrameder B6 (1-1-1) de Méderi',
                    'MAGNESIO. Ultramagnesio marino de Phytovit',
                    'MANEJO DEL STRESS. ADRENAL',
                    'MANEJO DEL STRESS. cPNI-11D',
                    'MANEJO DEL STRESS. cPNI-11S',
                    'MANEJO DEL STRESS. GABA 800 mg de VByotics',
                    'MANEJO DEL STRESS. Gaba Liposomal+L-Theanina',
                    'MANEJO DEL STRESS. L-TEANINA',
                    'MANEJO DEL STRESS. Magnocal',
                    'MANEJO DEL STRESS. NC+REL',
                    'MANEJO DEL STRESS. NEUROCONTROL',
                    'MANEJO DEL STRESS. PEGA STRESS de Pegaso',
                    'MANEJO DEL STRESS. PHENIBUT',
                    'MANEJO DEL STRESS. Phenibut de Yottaboost',
                    'MANEJO DEL STRESS. Picamilon',
                    'MANEJO DEL STRESS. Tintura de Ashwagandha de Eglé',
                    'MASTITIS. Lactobacillus fermentum + Lactoferrina',
                    'Mejorar densidad mitocondrial (Energía). Ácido alfa lipoico',
                    'Mejorar densidad mitocondrial (Energía). DHA',
                    'Mejorar densidad mitocondrial (Energía). Estimuladores T3',
                    'Mejorar densidad mitocondrial (Energía). L-Carnitina',
                    'Mejorar densidad mitocondrial (Energía). Vit D',
                    'Memoria. Cogni clear con CoQ10',
                    'MENOPAUSIA. Climaphyt de Méderi (1-1-1)',
                    'MENOPAUSIA. Meno Rhythm de CFN',
                    'MENOPAUSIA. Phyto estrogen plus de Solaray',
                    'MENOPAUSIA. Sage 2500 mg de Lamberts',
                    'MENOPAUSIA. SALVIA 2500 mg DE LAMBERTS',
                    'METOFAM. Gialmil',
                    'METOFAM. Hipraler',
                    'METOFAM. Minactil',
                    'METOFAM. Nadomat',
                    'METOFAM. Paviret',
                    'METOFAM. Sistroal',
                    'MIGRAÑA. Citrameder B6 de Méderi',
                    'MODULACIÓN DEL ER-ALFA. DIM (di-indolil-metano) de Airbiotic',
                    'MODULACIÓN DEL ER-ALFA. INDOL-3 CARBINOL',
                    'MULTIVIT. + MIN. fórmula magistral de farmacia 5 Caballeros 4',
                    'MULTIVIT. + MIN. fórmula magistral de farmacia 5 Caballeros 3',
                    'MULTIVIT. + MIN. HAIR-SKIN-NAILS de Solgar',
                    'MULTIVIT. + MIN. inmunomodulador de farmacia 5 Caballeros',
                    'MULTIVIT. + MIN. KADE-Vit de Méderi',
                    'MULTIVIT. + MIN. Liquid Multi de NowFoods',
                    'MULTIVIT. + MIN. Maxi-Hair de Lamberts',
                    'MULTIVIT. + MIN. Mineral complex de CFN (1-1-1)',
                    'MULTIVIT. + MIN. MOLIBDENO 400 mcg DE BONUSAN',
                    'MULTIVIT. + MIN. Multi Natal Activo de Bonusan (0-1-1)',
                    'MULTIVIT. + MIN. Multi Vital Forte Activo de Bonusan',
                    'MULTIVIT. + MIN. Multi-guard ADR de Lamberts (1-1-0)',
                    'MULTIVIT. + MIN. Multi-guard vit+minerales de Lamberts (0-1-0)',
                    'MULTIVIT. + MIN. MultiGuards para niños de Lamberts',
                    'MULTIVIT. + MIN. MULTIVITAL FORTE DE BONUSAN (0-1-0)',
                    'MULTIVIT. + MIN. MULTIVITAMINICO DE FARMACIA',
                    'MULTIVIT. + MIN. Multivitamínico vivo infantil de Terranova',
                    'MULTIVIT. + MIN. SELENIO DE CFN (0-1-0)',
                    'MULTIVIT. + MIN. Silicio G5 Original',
                    'MULTIVIT. + MIN. Vitamina C y D de Solaray',
                    'NEUROINFLAMACIÓN. Ácido fólico',
                    'NEUROINFLAMACIÓN. Betaína',
                    'NEUROINFLAMACIÓN. Citrato de Magnesio',
                    'NEUROINFLAMACIÓN. Colina',
                    'NEUROINFLAMACIÓN. PEA',
                    'NEUROINFLAMACIÓN. Vit B12',
                    'NEUROINFLAMACIÓN. Vit D',
                    'NOOTRÓPICOS. PANDORA DE BESTMELAB',
                    'Obesidad y sobrepeso. Glycinet + Adomelle',
                    'OMEGA 3. Aceite de Krill NKO niños',
                    'OMEGA 3. DHA 80% TG DE EGLÉ (0-1-0)',
                    'OMEGA 3. DHA NPD1 de Méderi 1000 mg',
                    'OMEGA 3. EPA/DHA 625/245 de KAL',
                    'OMEGA 3. NADH sublingual de CFN',
                    'OMEGA 3. para niños (puro omega)',
                    'OMEGA 3. Prim Omega de Bonusan',
                    'OMEGA 3. Veggunn',
                    'Oncología en general. Enterelle + Citogenex',
                    'Osteoporosis. Serobrain',
                    'OSTEOPOROSIS/OSTEOPENIA. Oste-on de Méderi',
                    'OSTEOPOROSIS/OSTEOPENIA. Osteonyl de Bonusan',
                    'OTROS SUPLEMENTOS. 2LARTH de LaboLife',
                    'OTROS SUPLEMENTOS. 2LC1 de LaboLife',
                    'OTROS SUPLEMENTOS. Abiprol',
                    'OTROS SUPLEMENTOS. Aller Perilla de Tongil',
                    'OTROS SUPLEMENTOS. Butirato de Synestia',
                    'OTROS SUPLEMENTOS. ButyCaps en cápsulas',
                    'OTROS SUPLEMENTOS. ButyMed de Méderi',
                    'OTROS SUPLEMENTOS. Cromo picolinato de Solaray',
                    'OTROS SUPLEMENTOS. Damiana de HSN',
                    'OTROS SUPLEMENTOS. Dermocare Pro de Bonusan',
                    'OTROS SUPLEMENTOS. DMG de Sura Vitasan',
                    'OTROS SUPLEMENTOS. EDC-4 de la farmacia El Globo',
                    'OTROS SUPLEMENTOS. Emo zeolita clinoptilolita Organik',
                    'OTROS SUPLEMENTOS. GABA 750mg de Kal',
                    'OTROS SUPLEMENTOS. HOUTTUYNIA CORDATA de Nutramedix',
                    'OTROS SUPLEMENTOS. Immun\'Age',
                    'OTROS SUPLEMENTOS. Ionic elements de laboratorios Pure planet',
                    'OTROS SUPLEMENTOS. LACTOFERRINA de Bonusan',
                    'OTROS SUPLEMENTOS. Lecitina de soja de Solgar',
                    'OTROS SUPLEMENTOS. MORINGA DE HOLOFIT',
                    'OTROS SUPLEMENTOS. MSM 1000 mg de CFN',
                    'OTROS SUPLEMENTOS. Mycoplex forte de Bonusan',
                    'OTROS SUPLEMENTOS. NAC 500 mg de Douglas',
                    'OTROS SUPLEMENTOS. NAC 600mg de EFNE',
                    'OTROS SUPLEMENTOS. NAC 600mg de lamberts',
                    'OTROS SUPLEMENTOS. Nerprem de Weltmont',
                    'OTROS SUPLEMENTOS. Oral Flora de Solaray',
                    'OTROS SUPLEMENTOS. OZOVIT MP DE COBAS',
                    'OTROS SUPLEMENTOS. Pectina modificada de SuraVitasan',
                    'OTROS SUPLEMENTOS. PRIMROSE OIL de Lamberts',
                    'OTROS SUPLEMENTOS. Proakk BPL1 de Eglé',
                    'OTROS SUPLEMENTOS. Regaliz desglicirrizado de CFN',
                    'OTROS SUPLEMENTOS. SAMe de Bonusan',
                    'OTROS SUPLEMENTOS. Serrapeptase de Solaray',
                    'OTROS SUPLEMENTOS. Shilajit de Holomega',
                    'OTROS SUPLEMENTOS. Shilajit de Synestia',
                    'OTROS SUPLEMENTOS. Spascupreel de Heel',
                    'OTROS SUPLEMENTOS. Tiras reactivas de orina',
                    'OTROS SUPLEMENTOS. Zeolith Med cápsulas',
                    'OVARIO POLIQUIST. INFERT. REGUL. DE REGLAS. CicloFitoFem Fertility de Eglé',
                    'OVARIO POLIQUIST. INFERT. REGUL. DE REGLAS. Crema de bio-identical estrogen cream',
                    'OVARIO POLIQUIST. INFERT. REGUL. DE REGLAS. Ergy yam de nutergia',
                    'OVARIO POLIQUIST. INFERT. REGUL. DE REGLAS. Soniase supra D Sobres',
                    'OVARIO POLIQUIST. INFERT. REGUL. DE REGLAS. Vitamina C 1000 mg',
                    'OVARIO POLIQUIST. INFERT. REGUL. DE REGLAS. Wild Yam de Solaray',
                    'PÁNCREAS. Curcuma longa',
                    'PÁNCREAS. Enzimas',
                    'PÁNCREAS. L-Triptófano',
                    'PÁNCREAS. Melatonina',
                    'PÁNCREAS. Probio Infants',
                    'PÁNCREAS. Vit D',
                    'PÁNCREAS. Zinc-Metionina',
                    'PARTO. Melatonina',
                    'PATÓGENOS. Allium Sativum',
                    'PATÓGENOS. Lactoferrina',
                    'PATÓGENOS. Manosa',
                    'Patología autoinmune. Serobioma + Citogenex',
                    'Patología Neurodegenerativa. Seriobioma',
                    'PATOLOGÍAS AUTOINMUNES. LDN',
                    'PÉRDIDA DE GRASA. ADIPO-BLOCK',
                    'PÉRDIDA DE GRASA. AMPK Metabolic de LifeExtension',
                    'PÉRDIDA DE GRASA. Fit 9 de Sascha',
                    'PÉRDIDA DE GRASA. GASSERI COMPLEX DE DERBOS',
                    'Permeabilidad intestinal. Enterelle',
                    'Permeabilidad intestinal. Serobioma',
                    'Plantas medicinales hepáticas 3 infusiones al día Cardo mariano',
                    'Plantas medicinales hepáticas 3 infusiones al día Alcachofera',
                    'Plantas medicinales hepáticas 3 infusiones al día Desmodium',
                    'Plantas medicinales hepáticas 3 infusiones al día Hepática',
                    'Plantas medicinales hepáticas 3 infusiones al día Rábano',
                    'Problemas respiratorios crónicos. Serioboma + acronelle',
                    'PROCINÉTICOS. BLOAT RELIEF',
                    'PROCINÉTICOS. Gut Motility de Enzymedica (0-1-1)',
                    'PROSTATITIS Y CAN. DE PRÓSTATA. Bikini Pro de Io',
                    'PROSTATITIS Y CAN. DE PRÓSTATA. Complejo de sabal (Saw Palmetto) y licopeno de Solgar',
                    'PROSTATITIS Y CAN. DE PRÓSTATA. Mico-Men de Hifas da Terra',
                    'PROSTATITIS Y CAN. DE PRÓSTATA. Saw Palmetto de Lamberts',
                    'PROSTATITIS Y CAN. DE PRÓSTATA. Saw Palmetto y Raíz de Ortiga NUTRILITE',
                    'PSORIASIS. Auxina A+E',
                    'PSORIASIS. Citogenex',
                    'PSORIASIS. Citrato de magnesio de Bonusan',
                    'PSORIASIS. DHA ORIGEN NPD-1',
                    'PSORIASIS. DMSO al 70%',
                    'PSORIASIS. Enterelle',
                    'PSORIASIS. MEL 13 PLUS de Neolife',
                    'PSORIASIS. MEL 13 RX de Neolife',
                    'PSORIASIS. Pranarom Cúrcuma Aceite Esencial',
                    'PSORIASIS. Selenio de CFN',
                    'PSORIASIS. Serobioma',
                    'PSORIASIS. Sumergir los pies y las manos en tierra',
                    'PSORIASIS. vENSTINLAR EN ESPUMA',
                    'PSORIASIS. Vitamina D3 en crema Soritan de Vitabay',
                    'PSORIASIS. VITAMINA D3 LÍQUIDA de KAL',
                    'PULMÓN (barrera). Betaglucanos',
                    'PULMÓN (barrera). cPNI-12D',
                    'PULMÓN (barrera). cPNI-12S',
                    'PULMÓN (barrera). cPNI-8U',
                    'PULMÓN (barrera). Cúrcuma',
                    'PULMÓN (barrera). Glutatión',
                    'PULMÓN (barrera). N-acetil cisteína',
                    'PULMÓN (barrera). Q-10',
                    'PULMÓN (barrera). Vit B',
                    'PULMÓN (barrera). Vit E',
                    'REGULACIÓN HPA Y SNS. CATECOLAMINAS cPNI-13',
                    'REGULACIÓN HPA Y SNS. CORTISOL cPNI-11',
                    'REGULACIÓN HPA Y SNS. Hypericum perforatum',
                    'REGULACIÓN HPA Y SNS. Ribes Nigrum Extracto',
                    'REGULACIÓN HPA Y SNS. Salvia Officinalis Extracto',
                    'REGULAR PARP. Ribosa Magnesio Vit B3',
                    'REND. DEPORTIVO. Amino PAG de Méderi',
                    'REND. DEPORTIVO. Batido de proteína Paleobull',
                    'REND. DEPORTIVO. BCAA BULK POWDERS',
                    'REND. DEPORTIVO. BCAA+GLUTAMINA de AMIX',
                    'REND. DEPORTIVO. CREATINA - BETA ALANINA DE NUTRINOVEX',
                    'REND. DEPORTIVO. Creatina de EFNE',
                    'REND. DEPORTIVO. L-carnitina Carnipure de HSN',
                    'REND. DEPORTIVO. L-carnitina de Solgar',
                    'REND. DEPORTIVO. MEGA MINERAL COMPLEX de Lamberts',
                    'REND. DEPORTIVO. Polvo alcalino de Bonusan',
                    'REND. DEPORTIVO. Proteína de suero hidrolizado aislada',
                    'REND. DEPORTIVO. Proteína whey de EFNE',
                    'REPARACIÓN BARRERAS. Fase 1',
                    'REPARACIÓN BARRERAS. Fase 2',
                    'REPARACIÓN BARRERAS. Fase 3',
                    'REPARACIÓN BARRERAS. Otros',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. Ácido fólico',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. Betaína + Colina',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. EPA-DHA',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. Melatonina',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. Multivitamínico (Multinatal)',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. SAMe',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. Vit B12',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. Vit D',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. Yodo',
                    'REPROGRAMACIÓN METABÓLICA GRUPOS METIL Y COFACTORES. Zinc',
                    'RESIST AL CORTISOL. cPNI-11D de Bonusan',
                    'RESIST AL CORTISOL. Hidroaltesona',
                    'RESISTENCIA A INSULINA. cPNI-9D',
                    'RESISTENCIA A INSULINA. cPNI-9S',
                    'RESISTENCIA A INSULINA. Cromo (picolinato)',
                    'RESISTENCIA A INSULINA. Glyconyl',
                    'RESISTENCIA A INSULINA. Mucuna Pruriens',
                    'RESISTENCIA A INSULINA. Omega 3',
                    'RESISTENCIA A INSULINA. Vit B',
                    'RESISTENCIA A INSULINA. Zinc',
                    'RESISTENCIA A LEPTINA. Colina',
                    'RESISTENCIA A LEPTINA. cPNI-12D',
                    'RESISTENCIA A LEPTINA. cPNI-12S',
                    'RESISTENCIA A LEPTINA. Ribosa',
                    'Resoleomics hepáticos. Allium Sativum',
                    'Resoleomics hepáticos. Bioflavonoides',
                    'Resoleomics hepáticos. Brassica Italica',
                    'Resoleomics hepáticos. Cardo mariano',
                    'Resoleomics hepáticos. Curcuma longa',
                    'Resoleomics hepáticos. GSH Glutatión',
                    'Resoleomics hepáticos. L-Glutamina',
                    'Resoleomics hepáticos. Omega 3',
                    'Rinitis. Isotonic',
                    'Rinitis. Spray ocular de Quinton',
                    'Rinitis. Vaporizaciones',
                    'SD Metabólico. Glycinet + Xantonet',
                    'Sensibilidad al gluten. Serobioma',
                    'Sensibilidad al gluten. Serobioma + Milonet',
                    'SIBO. Aceite de comino negro de Equisalud (1-1-1)',
                    'SIBO. Aceite de comino negro de Naturitas',
                    'SIBO. Aceite de orégano de Solaray',
                    'SIBO. ACEITE ESENCIAL PRANAROM AJEDREA 5ML',
                    'SIBO. ATRANTIL',
                    'SIBO. Berberina Arestata de CFN',
                    'SIBO. BERBERINA DE SOLARAY',
                    'SIBO. BETAINA HCL DE CFN (0-1-1)',
                    'SIBO. Caprilic complex de CFN',
                    'SIBO. CLEANintest de NPRO',
                    'SIBO. Cumanda de Nutramedix',
                    'SIBO. D-MANOSA 1000 mg de Solaray (0-0-1)',
                    'SIBO. Digest Digest Gold con ATPRO de Enzymedica',
                    'SIBO. EnteroLax-Jr FS de CFN',
                    'SIBO. Extracto de semilla de pomelo de Derbós',
                    'SIBO. FORZA VITALE QUINTA ESENCIA',
                    'SIBO. Gastrileo de Méderi',
                    'SIBO. Jugo de aloe vera de Tongil',
                    'SIBO. Menta piperita de Lamberts',
                    'SIBO. MOTILintest de NPRO',
                    'SIBO. NEOBIANACID',
                    'SIBO. OZONOintest de NPRO',
                    'SIBO. Para-Sit de Suravitasan',
                    'SIBO. PAU DE ARCO DE SURAVITASAN',
                    'SIBO. Peróxido',
                    'SIBO. POMEBOTIC DE DERBÓS',
                    'SIBO. Regacid de Soria Natural',
                    'SIBO. Samento de Nutramedix',
                    'SIBO. SPIRAXIN 200mg',
                    'SIBO. zumo de un limón',
                    'SÍNDROME PREMENSTRUAL. Cimífuga racemosa extracto de Bonusan',
                    'SÍNDROME PREMENSTRUAL. Infusiones de Angélica china (dong quai)',
                    'SÍNDROME PREMENSTRUAL. Infusiones de Kudzu',
                    'SÍNDROME PREMENSTRUAL. Infusiones de Regaliz',
                    'SÍNDROME PREMENSTRUAL. Kava Kava de Now',
                    'SOFOCOS MENOPAUSIA. Cimifuga racemosa',
                    'SOFOCOS MENOPAUSIA. Omega 3',
                    'SOFOCOS MENOPAUSIA. Vit D',
                    'SUSTANCIA P. 1400-4000',
                    'SUSTANCIA P. Griffonia Simplicifonia',
                    'SUSTANCIA P. Salvia Officinalis',
                    'TIROIDES. Guggul de Equisalud',
                    'TIROIDES. Selenium + Ashwagandha de EFNE',
                    'TIROIDES. Tyronyl de Bonusan',
                    'TRANSPORTE DE CUERPOS CETÓNICOS. L-carnitina',
                    'TRATAMIENTO COLESTEROL. Levadura de arroz rojo + CoQ10',
                    'TRATAMIENTO CON DMSO',
                    'TRATAMIENTO DE ELA. Agua de mar isotónica',
                    'TRATAMIENTO DE ELA. cPNI-1U',
                    'TRATAMIENTO DE ELA. L-Serina en polvo de Gold Nutrition',
                    'TRATAMIENTO DE ELA. Multi-guard vit+minerales',
                    'TRATAMIENTO DE ELA. NAC 600mg de Lamberts',
                    'TRATAMIENTO DE ELA. NADH de Birkmayer',
                    'TRATAMIENTO DE ELA. PEA (Palmitoiletanolamida)',
                    'TRATAMIENTO DE ELA. SOD 2000 Plus de Solaray',
                    'TRATAMIENTO DE ELA. VITAMINA D3 LÍQUIDA de KAL',
                    'TRATAMIENTO ESCLEROSIS MULTIPLE. Neur+bac de Zeus',
                    'TRATAMIENTO MUCOSA VAGINAL. D-manosa + ProÓvulos de GSE',
                    'TRATAMIENTO PARA LITIASIS. Herbensurina jarabe',
                    'TRATAMIENTO PARA LITIASIS. Rena support de sura vitasan',
                    'TRATAMIENTO PARA LITIASIS. Renalof de laboratorios Calalysis',
                    'Vaginitis polimicrobiana. Enterelle + Femelle',
                    'VIRUS DEL HERPES. Metilcobalamina de Solgar',
                    'VIRUS DEL HERPES. SAMe 400 de Bonusan',
                    'VIRUS DEL HERPES. ZINC DE SORIA NATURAL',
                    'VITAMINA B. B-Complex de Solaray',
                    'VITAMINA B. complex de Méderi',
                    'VITAMINA B. cucharadita de levadura nutricional',
                    'VITAMINA B. METAFOLIN FACTOR INTRÍNSECO de Douglas',
                    'VITAMINA B. NOW ÁCIDO PANTOTÉNICO 500MG',
                    'VITAMINA B. Now Foods Metilo B-12 1000mcg',
                    'VITAMINA B. Nutimetil B complex de Nutilab',
                    'VITAMINA C. comprimidos masticables de Myprotein',
                    'VITAMINA C. Rose Hips de Méderi (2-0-0)',
                    'VITAMINA C. 1000mg de Airbiotic liberación sostenida (2-1-0)',
                    'VITAMINA C. liposomada de EFNE',
                    'VITAMINA C. LIPOSOMAL DE LABORATORIOS SOLARAY (500MG)',
                    'VITAMINA C. LIPOSOMAL DE SOLARAY 500 MG',
                    'VITAMINA D. D3 LÍQUIDA de KAL 2000 UI',
                    'VITAMINA D. D3 4000 UI de CFN en comprimidos',
                    'VITAMINA D. Méderi de 4000 UI',
                ],
            ],
        ];
    }
}
